create warehouse healthcare_wh
with
warehouse_size='XSMALL'
auto_suspend=60
auto_resume=true
initially_suspended=true;

use warehouse healthcare_wh;

-- TASK 1 — Create Environment Context
CREATE DATABASE HEALTHCARE_DW;

CREATE SCHEMA HEALTHCARE_DW.SCHEMA_COMPARE_LAB;

use DATABASE HEALTHCARE_DW;

USE SCHEMA SCHEMA_COMPARE_LAB;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;


CREATE STAGE SCHEMA_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE TABLE HOSPITALS (
    HOSPITAL_ID NUMBER,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_ID NUMBER,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


CREATE TABLE TREATMENTS (
    TREATMENT_ID NUMBER,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_ID VARCHAR(50),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);


CREATE TABLE PATIENTS (
    PATIENT_ID NUMBER,
    PATIENT_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    AGE NUMBER,
    CITY VARCHAR(50)
);


CREATE TABLE INSURANCE_CLAIMS (
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER,
    HOSPITAL_ID NUMBER,
    TREATMENT_ID NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2)
);

COPY INTO HOSPITALS
FROM @SCHEMA_STAGE
FILES = ('hospital_hierarchy.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


COPY INTO TREATMENTS
FROM @SCHEMA_STAGE
FILES = ('treatment_hierarchy.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


COPY INTO PATIENTS
FROM @SCHEMA_STAGE
FILES = ('patients.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


COPY INTO INSURANCE_CLAIMS
FROM @SCHEMA_STAGE
FILES = ('insurance_claims.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


-- TASK 2
-- STAR_DIM_HOSPITAL

CREATE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER NOT NULL,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

-- TASK 3
-- STAR_DIM_TREATMENT

CREATE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER NOT NULL,
    TREATMENT_NAME VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST NUMBER(12,2)
);

-- TASK 4

INSERT INTO STAR_DIM_HOSPITAL
(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM HOSPITALS;


INSERT INTO STAR_DIM_TREATMENT
(
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    DIAGNOSIS_GROUP_NAME,
    STANDARD_COST
FROM TREATMENTS;


-- TASK 5

CREATE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER NOT NULL,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),

    FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES STAR_DIM_HOSPITAL(HOSPITAL_KEY),

    FOREIGN KEY (TREATMENT_KEY)
        REFERENCES STAR_DIM_TREATMENT(TREATMENT_KEY)
);

INSERT INTO STAR_FACT_CLAIMS
(
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    C.CLAIM_ID,
    C.CLAIM_DATE,
    C.PATIENT_ID,
    H.HOSPITAL_KEY,
    T.TREATMENT_KEY,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT
FROM INSURANCE_CLAIMS C
JOIN STAR_DIM_HOSPITAL H
    ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT T
    ON C.TREATMENT_ID = T.TREATMENT_ID;


-- TASK 6


CREATE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    NETWORK_ID NUMBER NOT NULL,
    NETWORK_NAME VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);


CREATE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID NUMBER NOT NULL,
    HOSPITAL_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    NETWORK_KEY NUMBER NOT NULL,

    FOREIGN KEY (NETWORK_KEY)
        REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);


-- TASK 7


CREATE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DIAGNOSIS_GROUP_ID VARCHAR(50) NOT NULL,
    DIAGNOSIS_GROUP_NAME VARCHAR(50)
);


CREATE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID NUMBER NOT NULL,
    TREATMENT_NAME VARCHAR(100),
    STANDARD_COST NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY NUMBER NOT NULL,

    FOREIGN KEY (DIAGNOSIS_GROUP_KEY)
        REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);

-- TASK 8
INSERT INTO SNOW_DIM_NETWORK
(
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
)
SELECT DISTINCT
    NETWORK_ID,
    NETWORK_NAME,
    NETWORK_DIRECTOR
FROM HOSPITALS;


INSERT INTO SNOW_DIM_HOSPITAL
(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    NETWORK_KEY
)
SELECT
    H.HOSPITAL_ID,
    H.HOSPITAL_NAME,
    H.CITY,
    H.STATE,
    N.NETWORK_KEY
FROM HOSPITALS H
JOIN SNOW_DIM_NETWORK N
    ON H.NETWORK_ID = N.NETWORK_ID;


INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP
(
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
)
SELECT DISTINCT
    DIAGNOSIS_GROUP_ID,
    DIAGNOSIS_GROUP_NAME
FROM TREATMENTS;


INSERT INTO SNOW_DIM_TREATMENT
(
    TREATMENT_ID,
    TREATMENT_NAME,
    STANDARD_COST,
    DIAGNOSIS_GROUP_KEY
)
SELECT
    T.TREATMENT_ID,
    T.TREATMENT_NAME,
    T.STANDARD_COST,
    D.DIAGNOSIS_GROUP_KEY
FROM TREATMENTS T
JOIN SNOW_DIM_DIAGNOSIS_GROUP D
    ON T.DIAGNOSIS_GROUP_ID = D.DIAGNOSIS_GROUP_ID;




-- TASK 9

CREATE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID VARCHAR(50),
    CLAIM_DATE DATE,
    PATIENT_ID NUMBER NOT NULL,
    HOSPITAL_KEY NUMBER,
    TREATMENT_KEY NUMBER,
    CLAIMED_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),

    FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),

    FOREIGN KEY (TREATMENT_KEY)
        REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY)
);


INSERT INTO SNOW_FACT_CLAIMS
(
    CLAIM_ID,
    CLAIM_DATE,
    PATIENT_ID,
    HOSPITAL_KEY,
    TREATMENT_KEY,
    CLAIMED_AMOUNT,
    APPROVED_AMOUNT
)
SELECT
    C.CLAIM_ID,
    C.CLAIM_DATE,
    C.PATIENT_ID,
    H.HOSPITAL_KEY,
    T.TREATMENT_KEY,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT
FROM INSURANCE_CLAIMS C
JOIN SNOW_DIM_HOSPITAL H
    ON C.HOSPITAL_ID = H.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT T
    ON C.TREATMENT_ID = T.TREATMENT_ID;





-- TASK 10

SELECT
    T.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_TREATMENT T
    ON F.TREATMENT_KEY = T.TREATMENT_KEY
GROUP BY T.DIAGNOSIS_GROUP_NAME
ORDER BY T.DIAGNOSIS_GROUP_NAME;


-- TASK 11

SELECT
    D.DIAGNOSIS_GROUP_NAME,
    SUM(F.CLAIMED_AMOUNT) AS TOTAL_CLAIMED_AMOUNT,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_TREATMENT T
    ON F.TREATMENT_KEY = T.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP D
    ON T.DIAGNOSIS_GROUP_KEY = D.DIAGNOSIS_GROUP_KEY
GROUP BY D.DIAGNOSIS_GROUP_NAME
ORDER BY D.DIAGNOSIS_GROUP_NAME;


-- TASK 12

SELECT
    H.NETWORK_DIRECTOR,
    COUNT(*) AS TOTAL_CLAIMS_HANDLED,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS F
JOIN STAR_DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.NETWORK_DIRECTOR;


-- TASK 12
-- SNOWFLAKE SCHEMA

SELECT
    N.NETWORK_DIRECTOR,
    COUNT(*) AS TOTAL_CLAIMS_HANDLED,
    SUM(F.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS F
JOIN SNOW_DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK N
    ON H.NETWORK_KEY = N.NETWORK_KEY
GROUP BY N.NETWORK_DIRECTOR;



-- select * from star_dim_hospital;
-- task 13
UPDATE STAR_DIM_HOSPITAL s
SET NETWORK_DIRECTOR = 'Dr. Anand'
FROM HOSPITALS h
WHERE s.HOSPITAL_ID = h.HOSPITAL_ID
  AND h.NETWORK_ID = 10;


UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_ID = 10
  AND NETWORK_DIRECTOR = 'Dr. Ramesh';


  
-- VERIFY STAR SCHEMA
SELECT *
FROM STAR_DIM_HOSPITAL
WHERE NETWORK_NAME = 'Apollo Healthcare Group';


-- VERIFY SNOWFLAKE SCHEMA
SELECT *
FROM SNOW_DIM_NETWORK
WHERE NETWORK_ID = 10;



-- ================================================================
-- TASK 14 — Full Architecture Record Audit & Schema Comparison
-- ================================================================

SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_HOSPITAL' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_HOSPITAL

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_TREATMENT',
    COUNT(*)
FROM STAR_DIM_TREATMENT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_CLAIMS',
    COUNT(*)
FROM STAR_FACT_CLAIMS

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_NETWORK',
    COUNT(*)
FROM SNOW_DIM_NETWORK

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_HOSPITAL',
    COUNT(*)
FROM SNOW_DIM_HOSPITAL

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_DIAGNOSIS_GROUP',
    COUNT(*)
FROM SNOW_DIM_DIAGNOSIS_GROUP

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_TREATMENT',
    COUNT(*)
FROM SNOW_DIM_TREATMENT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_CLAIMS',
    COUNT(*)
FROM SNOW_FACT_CLAIMS;
