-- TASK 1 — CREATE DATABASE AND SCHEMA CONTEXT

CREATE DATABASE RETAIL_SCHEMAS_DW;

USE DATABASE RETAIL_SCHEMAS_DW;

CREATE SCHEMA SCHEMA_COMPARISON;

USE SCHEMA SCHEMA_COMPARISON;

CREATE WAREHOUSE WH_SCHEMA
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE WH_SCHEMA;

CREATE STAGE SCHEMA_STAGE;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

-- TASK 2 — CREATE STAR_DIM_STORE

CREATE TABLE STAR_DIM_STORE (
    STORE_KEY NUMBER PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1 ORDER,
    STORE_ID NUMBER NOT NULL,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    REGION_NAME VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

-- TASK 3 — CREATE STAR_DIM_PRODUCT


CREATE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY NUMBER PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1 ORDER,
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME VARCHAR(50),
    UNIT_PRICE NUMBER(10,2)
);

CREATE TABLE STAR_DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

COPY INTO STAR_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_NAME,
    REGIONAL_MANAGER
)
FROM @SCHEMA_STAGE
FILES = ('regions_and_stores.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


COPY INTO STAR_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    SUBCATEGORY_NAME,
    CATEGORY_NAME,
    UNIT_PRICE
)
FROM @SCHEMA_STAGE
FILES = ('product_hierarchy.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


COPY INTO STAR_DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE
)
FROM @SCHEMA_STAGE
FILES = ('customers.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


CREATE TABLE SALES_TRANSACTION (
    TRANSACTION_ID VARCHAR PRIMARY KEY,
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER NOT NULL,
    STORE_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2)
);


COPY INTO SALES_TRANSACTION
FROM @SCHEMA_STAGE
FILES = ('sales_transactions.csv')
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


-- TASK 5 — CREATE STAR_FACT_SALES


CREATE TABLE STAR_FACT_SALES (
    SALES_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID NUMBER NOT NULL,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES STAR_DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (STORE_KEY)
        REFERENCES STAR_DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES STAR_DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO STAR_FACT_SALES
(
    TRANSACTION_ID,
    TRANSACTION_DATE,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    s.TRANSACTION_ID,
    s.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    st.STORE_KEY,
    p.PRODUCT_KEY,
    s.QUANTITY,
    s.QUANTITY * s.UNIT_PRICE AS TOTAL_AMOUNT
FROM SALES_TRANSACTION s
JOIN STAR_DIM_CUSTOMER c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
JOIN STAR_DIM_STORE st
    ON s.STORE_ID = st.STORE_ID
JOIN STAR_DIM_PRODUCT p
    ON s.PRODUCT_ID = p.PRODUCT_ID;


-- TASK 6 — CREATE NORMALIZED STORE HIERARCHY

CREATE TABLE SNOW_DIM_REGION (
    REGION_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    REGION_NAME VARCHAR,
    REGIONAL_MANAGER VARCHAR
);


CREATE TABLE SNOW_DIM_STORE (
    STORE_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    STORE_ID NUMBER NOT NULL,
    STORE_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION_KEY NUMBER NOT NULL,

    FOREIGN KEY (REGION_KEY)
        REFERENCES SNOW_DIM_REGION(REGION_KEY)
);

-- TASK 7 — CREATE NORMALIZED PRODUCT HIERARCHY


CREATE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    CATEGORY_NAME VARCHAR
);


CREATE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    SUBCATEGORY_NAME VARCHAR,
    CATEGORY_KEY NUMBER NOT NULL,

    FOREIGN KEY (CATEGORY_KEY)
        REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);


CREATE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY NUMBER PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR,
    UNIT_PRICE NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER NOT NULL,

    FOREIGN KEY (SUBCATEGORY_KEY)
        REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);




-- TASK 8 — POPULATE SNOWFLAKE DIMENSIONS

-- REGION

INSERT INTO SNOW_DIM_REGION
(
    REGION_NAME,
    REGIONAL_MANAGER
)
SELECT DISTINCT
    REGION_NAME,
    REGIONAL_MANAGER
FROM STAR_DIM_STORE;


-- STORE

INSERT INTO SNOW_DIM_STORE
(
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION_KEY
)
SELECT DISTINCT
    s.STORE_ID,
    s.STORE_NAME,
    s.CITY,
    s.STATE,
    r.REGION_KEY
FROM STAR_DIM_STORE s
JOIN SNOW_DIM_REGION r
    ON s.REGION_NAME = r.REGION_NAME;


-- CATEGORY

INSERT INTO SNOW_DIM_CATEGORY
(
    CATEGORY_NAME
)
SELECT DISTINCT
    CATEGORY_NAME
FROM STAR_DIM_PRODUCT;


-- SUBCATEGORY

INSERT INTO SNOW_DIM_SUBCATEGORY
(
    SUBCATEGORY_NAME,
    CATEGORY_KEY
)
SELECT DISTINCT
    p.SUBCATEGORY_NAME,
    c.CATEGORY_KEY
FROM STAR_DIM_PRODUCT p
JOIN SNOW_DIM_CATEGORY c
    ON p.CATEGORY_NAME = c.CATEGORY_NAME;


-- PRODUCT

INSERT INTO SNOW_DIM_PRODUCT
(
    PRODUCT_ID,
    PRODUCT_NAME,
    UNIT_PRICE,
    SUBCATEGORY_KEY
)
SELECT DISTINCT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.UNIT_PRICE,
    sc.SUBCATEGORY_KEY
FROM STAR_DIM_PRODUCT p
JOIN SNOW_DIM_SUBCATEGORY sc
    ON p.SUBCATEGORY_NAME = sc.SUBCATEGORY_NAME;



    -- TASK 9 — CREATE SNOW_FACT_SALES

CREATE TABLE SNOW_FACT_SALES (
    SALES_KEY NUMBER PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1 ORDER,
    TRANSACTION_ID VARCHAR NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    STORE_KEY NUMBER NOT NULL,
    PRODUCT_KEY NUMBER NOT NULL,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER,

    FOREIGN KEY (STORE_KEY)
        REFERENCES SNOW_DIM_STORE(STORE_KEY),

    FOREIGN KEY (PRODUCT_KEY)
        REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY)
);

INSERT INTO SNOW_FACT_SALES
(
    TRANSACTION_ID,
    CUSTOMER_ID,
    STORE_KEY,
    PRODUCT_KEY,
    QUANTITY,
    UNIT_PRICE
)
SELECT
    s.TRANSACTION_ID,
    s.CUSTOMER_ID,
    st.STORE_KEY,
    p.PRODUCT_KEY,
    s.QUANTITY,
    s.UNIT_PRICE
FROM SALES_TRANSACTION s
JOIN SNOW_DIM_PRODUCT p
    ON s.PRODUCT_ID = p.PRODUCT_ID
JOIN SNOW_DIM_STORE st
    ON s.STORE_ID = st.STORE_ID;

-- TASK 10 — STAR SCHEMA ANALYTICS

SELECT
    st.REGION_NAME,
    p.CATEGORY_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES s
JOIN STAR_DIM_PRODUCT p
    ON s.PRODUCT_KEY = p.PRODUCT_KEY
JOIN STAR_DIM_STORE st
    ON s.STORE_KEY = st.STORE_KEY
GROUP BY
    st.REGION_NAME,
    p.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;


-- TASK 11 — SNOWFLAKE SCHEMA ANALYTICS


SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(s.QUANTITY * s.UNIT_PRICE) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES s
JOIN SNOW_DIM_STORE st
    ON s.STORE_KEY = st.STORE_KEY
JOIN SNOW_DIM_REGION r
    ON st.REGION_KEY = r.REGION_KEY
JOIN SNOW_DIM_PRODUCT p
    ON s.PRODUCT_KEY = p.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY sc
    ON p.SUBCATEGORY_KEY = sc.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY c
    ON sc.CATEGORY_KEY = c.CATEGORY_KEY
GROUP BY
    r.REGION_NAME,
    c.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;




-- TASK 13 — REGIONAL MANAGER SALES PERFORMANCE

SELECT
    st.REGIONAL_MANAGER,
    SUM(s.QUANTITY) AS TOTAL_ITEMS_SOLD,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES s
JOIN STAR_DIM_STORE st
    ON s.STORE_KEY = st.STORE_KEY
GROUP BY
    st.REGIONAL_MANAGER
ORDER BY TOTAL_SALES_AMOUNT DESC;



-- TASK 14 — FULL WAREHOUSE ARCHITECTURE AUDIT

SELECT
    'Star Schema' AS SCHEMA_TYPE,
    'STAR_DIM_STORE' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM STAR_DIM_STORE

UNION ALL

SELECT
    'Star Schema',
    'STAR_DIM_PRODUCT',
    COUNT(*)
FROM STAR_DIM_PRODUCT

UNION ALL

SELECT
    'Star Schema',
    'STAR_FACT_SALES',
    COUNT(*)
FROM STAR_FACT_SALES

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_REGION',
    COUNT(*)
FROM SNOW_DIM_REGION

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_STORE',
    COUNT(*)
FROM SNOW_DIM_STORE

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_CATEGORY',
    COUNT(*)
FROM SNOW_DIM_CATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_SUBCATEGORY',
    COUNT(*)
FROM SNOW_DIM_SUBCATEGORY

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_DIM_PRODUCT',
    COUNT(*)
FROM SNOW_DIM_PRODUCT

UNION ALL

SELECT
    'Snowflake Schema',
    'SNOW_FACT_SALES',
    COUNT(*)
FROM SNOW_FACT_SALES;
